# Environment variables
# - HEROKU_API_KEY
# - HEROKU_APP_NAME

version: 2
jobs:
  python_deploy:
    docker:
      - image: circleci/python:3.7-stretch

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: heroku deploy
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
workflows:
  version: 2
  python_flows:
    jobs:
      - python_deploy:
          filters:
            branches:
              only: master
